### PR TITLE
add German translation

### PR DESCRIPTION
**Pull request by SubOptimal**

### CODE REVIEW

**Comment by chrisbolin** [comment]
Danke! Sorry I didn't see this until now!

**Comment by chrisbolin** [comment]
@SubOptimal how would you translate these two lines into german?

- Enable Airplane Mode.
- Disconnect to continue.

I could use Google translate, but thought I would ask you!

**Comment by SubOptimal** [comment]
Enable Airplane Modus - Flugzeugmodus aktivieren
Disconnect to continue - Internetverbindung trennen um fortzufahren

'Internetverbindung' (internet connection) is needed to make the context clear, otherwise is to ambiguous.

**Comment by chrisbolin** [comment]
@SubOptimal sounds awesome. i'll get this up today.

**Pull request merged**
